name: iOS Build Pax Rio Verde

on:
  push:
    branches: [ main, master ]

env:
  # Isso remove o aviso de depreciação do Node.js 20
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Apple Certificate
        env:
          P12_CERTIFICATE: ${{ secrets.P12_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Decodifica o certificado
          echo "$P12_CERTIFICATE" | base64 --decode > certificate.p12
          
          # Cria e configura o chaveiro temporário
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          
          # Importa usando aspas simples para proteger a senha
          security import certificate.p12 -k build.keychain -P '$P12_PASSWORD' -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Install Provisioning Profile
        env:
          MOBILEPROVISION: ${{ secrets.MOBILEPROVISION }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$MOBILEPROVISION" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew :shared:assembleRelease 

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-output
          path: build/ios/ipa/*.ipa
